# Generated by Django 5.0.7 on 2024-07-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infobuttoncontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infoheadercontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infoimagecontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infotextcontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]
