# Generated by Django 5.0.7 on 2024-08-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialistmodel',
            options={'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
    ]
