# Generated by Django 5.0.7 on 2024-08-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_categorymodel_alter_specialistmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'Категории видео'},
        ),
    ]
