# Generated by Django 5.0.7 on 2024-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_categorymodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='page',
            field=models.CharField(blank=True, choices=[('hip', 'Протез бедра'), ('leg', 'Протез голени'), ('arm', 'Протез руки'), ('sport', 'Протез спортивный'), ('swim', 'Протез купальный'), ('main', 'Главная'), ('about', 'О компании'), ('interview', 'Интервью с клиентами')], max_length=30, null=True, verbose_name='Страница'),
        ),
    ]
