# Generated by Django 5.0.7 on 2024-08-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_rename_picture_videomodel_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='page',
        ),
    ]
