# Generated by Django 5.0.7 on 2024-07-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbuttoncontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainheadercontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainimagecontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintextcontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]
