# Generated by Django 5.0.7 on 2024-07-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leg_prosthesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legbuttoncontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legheadercontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legimagecontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legtextcontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]
