# Generated by Django 5.0.7 on 2024-07-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand_prosthesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbuttoncontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='handheadercontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='handimagecontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='handtextcontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]
