# Generated by Django 5.0.7 on 2024-07-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim_prosthesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimbuttoncontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='swimheadercontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='swimimagecontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='swimtextcontent',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]
