"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
if DEBUG:
    ALLOWED_HOSTS = ['*']
    CORS_ALLOW_ALL_ORIGINS = True
    CSRF_TRUSTED_ORIGINS = ['https://ab9f-188-68-160-86.ngrok-free.app']
else:
    ALLOWED_HOSTS = ['moreprotezov.ru', 'localhost', '0.0.0.0', '127.0.0.1', '95.163.228.162', 'http://localhost:3000 ']
    CSRF_TRUSTED_ORIGINS = ['https://moreprotezov.ru',
                            'http://moreprotezov.ru',
                            'https://0.0.0.0',
                            'http://0.0.0.0',
                            'https://127.0.0.1',
                            'http://127.0.0.1',
                            'http://95.163.228.162',
                            'https://95.163.228.162', ]
    CORS_ALLOWED_ORIGINS = ['https://moreprotezov.ru',
                            'http://moreprotezov.ru',
                            'https://0.0.0.0',
                            'http://0.0.0.0',
                            'https://127.0.0.1',
                            'http://127.0.0.1',
                            'http://95.163.228.162',
                            'https://95.163.228.162']
# Application definition
CORS_ALLOW_METHODS = (
        "DELETE",
        "GET",
        "OPTIONS",
        "PATCH",
        "POST",
        "PUT",
)

CORS_ALLOW_HEADERS = (
        "accept",
        "authorization",
        "content-type",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
)
INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        "corsheaders",
        'rest_framework',
        'coreapp',
        'main_page',
        'blog',
        'nested_admin',
        'django_ckeditor_5'
]

MIDDLEWARE = [
        "corsheaders.middleware.CorsMiddleware",
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
        {
                'BACKEND': 'django.template.backends.django.DjangoTemplates',
                'DIRS': [os.path.join(BASE_DIR, 'templates')],
                'APP_DIRS': True,
                'OPTIONS': {
                        'context_processors': [
                                'django.template.context_processors.debug',
                                'django.template.context_processors.request',
                                'django.contrib.auth.context_processors.auth',
                                'django.contrib.messages.context_processors.messages',
                        ],
                },
        },
]

WSGI_APPLICATION = 'shop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
        'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
        }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
        {
                'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
                'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
                'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
                'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
if DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'production_static')
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    DEFAULT_DOMAIN = "http://127.0.0.1:8000/"
else:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'production_static')]
    STATIC_ROOT = "/var/www/html/static"
    MEDIA_ROOT = "/var/www/html/media"
    DEFAULT_DOMAIN = "https://moreprotezov.ru/"
URL_NOTIFICATION = 'http://localhost:3000/next-api/revalidate'
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
customColorPalette = [
        {
                'color': 'hsl(4, 90%, 58%)',
                'label': 'Red'
        },
        {
                'color': 'hsl(340, 82%, 52%)',
                'label': 'Pink'
        },
        {
                'color': 'hsl(291, 64%, 42%)',
                'label': 'Purple'
        },
        {
                'color': 'hsl(262, 52%, 47%)',
                'label': 'Deep Purple'
        },
        {
                'color': 'hsl(231, 48%, 48%)',
                'label': 'Indigo'
        },
        {
                'color': 'hsl(207, 90%, 54%)',
                'label': 'Blue'
        },
]
CKEDITOR_5_FILE_STORAGE = "shop.file_storage.CustomStorage"  # optional
CKEDITOR_5_CONFIGS = {
        'default': {
                'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                            'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
                'language': 'ru',

        },
        'extends': {
                'baseHref': 'https://ab9f-188-68-160-86.ngrok-free.app',
                'blockToolbar': [
                        'paragraph', 'heading1', 'heading2', 'heading3',
                        '|',
                        'bulletedList', 'numberedList',
                        '|',
                        'blockQuote',
                ],
                'toolbar': ['heading', '|', '|', 'bold', 'italic', 'link', 'underline',
                            'insertImage',
                            'bulletedList', 'numberedList', 'fontColor', 'fontBackgroundColor'],
                'image': {
                        'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                                    'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|'],
                        'styles': [
                                'full',
                                'side',
                                'alignLeft',
                                'alignRight',
                                'alignCenter',
                        ]

                },
                'table': {
                        'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells',
                                           'tableProperties', 'tableCellProperties'],
                        'tableProperties': {
                                'borderColors': customColorPalette,
                                'backgroundColors': customColorPalette
                        },
                        'tableCellProperties': {
                                'borderColors': customColorPalette,
                                'backgroundColors': customColorPalette
                        }
                },
                'heading': {
                        'options': [
                                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1',
                                 'class': 'ck-heading_heading1'},
                                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2',
                                 'class': 'ck-heading_heading2'},
                                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3',
                                 'class': 'ck-heading_heading3'}
                        ]
                },
                'language': 'ru',
        },
        'list': {
                'properties': {
                        'styles': 'true',
                        'startIndex': 'true',
                        'reversed': 'true',
                }
        }
}
