# Generated by Django 5.0.7 on 2024-08-02 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название протеза')),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание протеза')),
                ('description', models.CharField(max_length=1000, verbose_name='Информация о протезе')),
                ('image', models.ImageField(upload_to='prostheses_type/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Протез',
                'verbose_name_plural': 'Протезы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=70, verbose_name='Название секции')),
                ('description', models.CharField(blank=True, default=' ', max_length=120, verbose_name='Описание секции(можно оставить пустым)')),
                ('page', models.CharField(choices=[('product', 'Протезы'), ('main', 'Главная'), ('about', 'О компании'), ('interview', 'Интервью с клиентами'), ('contacts', 'Контакты')], max_length=30, null=True, verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=90, verbose_name='Фамилия Имя Отчество')),
                ('photo', models.ImageField(upload_to='specialists/', verbose_name='Фотография')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
                ('bio', models.TextField(verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Общая информация о содержании картинки')),
                ('data', models.ImageField(blank=True, null=True, upload_to='page_images/', verbose_name='Изображение')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('tag_dev', models.CharField(max_length=30, verbose_name='Тэг для разработки контента')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='Общая информация о содержании заголовка')),
                ('type', models.CharField(blank=True, default=' ', max_length=20, null=True, verbose_name='Тип заголовка(h1, h2, h3, h4, h5)')),
                ('data', models.TextField(blank=True, default=' ', verbose_name='Текст заголовка')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('tag_dev', models.CharField(max_length=30, verbose_name='Тэг для разработки контента')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовки',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ButtonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=' ', max_length=60, null=True, verbose_name='Общая информация о содержании кнопки')),
                ('data', models.TextField(blank=True, default=' ', null=True, verbose_name='Текст кнопки')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='button_images/', verbose_name='Изображение для кнопки')),
                ('tag_dev', models.CharField(max_length=30, verbose_name='Тэг для разработки контента')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'О компании',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Главная',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Страница протеза',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=' ', max_length=60, null=True, verbose_name='Общая информация о тексте')),
                ('data', models.TextField(blank=True, default=' ', null=True, verbose_name='Содержание текста')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('tag_dev', models.CharField(max_length=30, verbose_name='Тэг для разработки контента')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Текстовый контент',
                'verbose_name_plural': 'Текстовый контент',
                'abstract': False,
            },
        ),
    ]
