# Generated by Django 5.0.7 on 2024-08-16 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_dev', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание')),
                ('button', models.CharField(blank=True, max_length=30, null=True, verbose_name='Кнопка')),
                ('accept', models.CharField(blank=True, max_length=200, null=True, verbose_name='Согласие на отправку формы')),
            ],
            options={
                'verbose_name': 'экземпляр формы',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='ListRelatedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_dev', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг')),
                ('description', models.CharField(max_length=70, verbose_name='Описание связанного списка')),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Связанный список',
                'verbose_name_plural': 'Связанные списки',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=100, verbose_name='Название секции')),
                ('description', models.CharField(blank=True, default=' ', max_length=120, verbose_name='Описание секции(можно оставить пустым)')),
                ('page', models.CharField(choices=[('hip', 'Протез бедра'), ('leg', 'Протез голени'), ('arm', 'Протез руки'), ('sport', 'Протез спортивный'), ('swim', 'Протез купальный'), ('main', 'Главная'), ('about', 'О компании'), ('interview', 'Интервью с клиентами'), ('contacts', 'Контакты'), ('footer', 'Футер')], max_length=30, null=True, verbose_name='Страница')),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='поле 1')),
                ('field_2', models.TextField(blank=True, max_length=500, null=True, verbose_name='поле 2')),
                ('field_3', models.TextField(blank=True, max_length=5000, null=True, verbose_name='поле 3')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='relationlist_images/', verbose_name='Изображение')),
                ('list_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main_page.listrelatedcontent', verbose_name='Связанный список')),
            ],
            options={
                'verbose_name': 'элемент',
                'verbose_name_plural': 'элементы',
            },
        ),
        migrations.CreateModel(
            name='PlaceHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=30, null=True, verbose_name='текст')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='main_page.formcontent', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'экземпляр поля',
                'verbose_name_plural': 'Поля формы',
            },
        ),
        migrations.AddField(
            model_name='listrelatedcontent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция'),
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Общая информация о содержании картинки')),
                ('data', models.ImageField(blank=True, null=True, upload_to='page_images/', verbose_name='Изображение')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('tag_dev', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Общая информация о содержании заголовка')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип заголовка(h1, h2, h3, h4, h5)')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Текст заголовка')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('tag_dev', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовки',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formcontent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция'),
        ),
        migrations.CreateModel(
            name='ButtonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=' ', max_length=60, null=True, verbose_name='Общая информация о содержании кнопки')),
                ('field_1', models.CharField(blank=True, max_length=70, null=True, verbose_name='Текст кнопки')),
                ('field_2', models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Текст кнопки')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='button_images/', verbose_name='Изображение для кнопки')),
                ('tag_dev', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'О компании',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='ArmPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Протез руки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Контакты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='FooterPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Футер',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='HipPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Протез бедра',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='LegPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Протез голени',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Главная',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='SportPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Протез спортивный',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='SwimPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Протез купальный',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Общая информация о тексте')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Содержание текста')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('tag_dev', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Текстовый контент',
                'verbose_name_plural': 'Текстовый контент',
                'abstract': False,
            },
        ),
    ]
