# Generated by Django 5.0.7 on 2024-08-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttoncontent',
            name='tag_dev',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг для разработки контента'),
        ),
        migrations.AlterField(
            model_name='headercontent',
            name='tag_dev',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг для разработки контента'),
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='tag_dev',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг для разработки контента'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='tag_dev',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг для разработки контента'),
        ),
    ]
