# Generated by Django 5.0.7 on 2024-08-02 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_buttoncontent_tag_dev_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListRelatedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_dev', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг для разработки контента')),
                ('description', models.CharField(max_length=60, verbose_name='Описание связанного списка')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Связанный список',
                'verbose_name_plural': 'Связанные списки',
            },
        ),
        migrations.CreateModel(
            name='FieldContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Содержание')),
                ('list_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='main_page.listrelatedcontent', verbose_name='Связанный список')),
            ],
            options={
                'verbose_name': 'содержание',
            },
        ),
    ]
