# Generated by Django 5.0.7 on 2024-08-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_listrelatedcontent_fieldcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialist',
        ),
    ]
