# Generated by Django 5.0.7 on 2024-08-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_delete_specialist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldcontent',
            options={'verbose_name': 'элемент', 'verbose_name_plural': 'элементы'},
        ),
        migrations.RemoveField(
            model_name='fieldcontent',
            name='text',
        ),
        migrations.AddField(
            model_name='fieldcontent',
            name='field_1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='поле 1'),
        ),
        migrations.AddField(
            model_name='fieldcontent',
            name='field_2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='поле 2'),
        ),
        migrations.AddField(
            model_name='fieldcontent',
            name='field_3',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='поле 3'),
        ),
        migrations.AddField(
            model_name='fieldcontent',
            name='field_4',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='поле 2'),
        ),
    ]
