# Generated by Django 5.0.7 on 2024-08-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_fieldcontent_options_remove_fieldcontent_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
