# Generated by Django 5.0.7 on 2024-08-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_section_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcontent',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listrelatedcontent',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
