# Generated by Django 5.0.7 on 2024-08-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_fieldcontent_position_listrelatedcontent_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldcontent',
            name='field_4',
        ),
        migrations.AddField(
            model_name='fieldcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='relationlist_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='listrelatedcontent',
            name='description',
            field=models.CharField(max_length=70, verbose_name='Описание связанного списка'),
        ),
    ]
