# Generated by Django 5.0.7 on 2024-08-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_remove_fieldcontent_field_4_fieldcontent_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttoncontent',
            name='tag_dev',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='headercontent',
            name='tag_dev',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='tag_dev',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='listrelatedcontent',
            name='tag_dev',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='tag_dev',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг'),
        ),
        migrations.CreateModel(
            name='FormContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_dev', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тэг')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('button', models.CharField(blank=True, max_length=30, null=True, verbose_name='Кнопка')),
                ('accept', models.CharField(blank=True, max_length=200, null=True, verbose_name='Согласие на отправку формы')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Экземпляр формы',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='PlaceHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=30, null=True, verbose_name='текст')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='main_page.formcontent', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'поле',
                'verbose_name_plural': 'Поля формы',
            },
        ),
    ]
