# Generated by Django 5.0.7 on 2024-08-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_alter_formcontent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeholder',
            options={'verbose_name': 'экземпляр поля', 'verbose_name_plural': 'Поля формы'},
        ),
        migrations.AlterField(
            model_name='fieldcontent',
            name='field_2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='поле 2'),
        ),
        migrations.AlterField(
            model_name='fieldcontent',
            name='field_3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='поле 3'),
        ),
    ]
