# Generated by Django 5.0.7 on 2024-08-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_alter_placeholder_options_alter_fieldcontent_field_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcontent',
            name='field_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='поле 1'),
        ),
        migrations.AlterField(
            model_name='fieldcontent',
            name='field_2',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='поле 2'),
        ),
        migrations.AlterField(
            model_name='fieldcontent',
            name='field_3',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='поле 3'),
        ),
    ]
