# Generated by Django 5.0.7 on 2024-08-03 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_alter_fieldcontent_field_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcontent',
            name='list_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main_page.listrelatedcontent', verbose_name='Связанный список'),
        ),
    ]
