# Generated by Django 5.0.7 on 2024-08-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_alter_fieldcontent_list_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default=' ', max_length=100, verbose_name='Название секции'),
        ),
    ]
