# Generated by Django 5.0.7 on 2024-08-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_alter_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttoncontent',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='headercontent',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='Текст заголовка'),
        ),
        migrations.AlterField(
            model_name='headercontent',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Общая информация о содержании заголовка'),
        ),
        migrations.AlterField(
            model_name='headercontent',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип заголовка(h1, h2, h3, h4, h5)'),
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Общая информация о содержании картинки'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание текста'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Общая информация о тексте'),
        ),
    ]
