# Generated by Django 5.0.7 on 2024-08-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_alter_buttoncontent_data_alter_headercontent_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductPage',
        ),
        migrations.CreateModel(
            name='ArmPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Протез руки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='HipPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Протез бедра',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='LegPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Протез голени',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='SportPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Спортивный протез',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='SwimPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Купальный протез',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(choices=[('hip', 'Протез бедра'), ('leg', 'Протез голени'), ('arm', 'Протез руки'), ('sport', 'Спортивный протез'), ('swim', 'Купальный протез'), ('main', 'Главная'), ('about', 'О компании'), ('interview', 'Интервью с клиентами'), ('contacts', 'Контакты')], max_length=30, null=True, verbose_name='Страница'),
        ),
    ]
