# Generated by Django 5.0.7 on 2024-08-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_delete_product_delete_productpage_armpage_hippage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportpage',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Протез спортивный'},
        ),
        migrations.AlterModelOptions(
            name='swimpage',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Протез купальный'},
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(choices=[('hip', 'Протез бедра'), ('leg', 'Протез голени'), ('arm', 'Протез руки'), ('sport', 'Протез спортивный'), ('swim', 'Протез купальный'), ('main', 'Главная'), ('about', 'О компании'), ('interview', 'Интервью с клиентами'), ('contacts', 'Контакты')], max_length=30, null=True, verbose_name='Страница'),
        ),
    ]
