# Generated by Django 5.0.7 on 2024-08-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_alter_sportpage_options_alter_swimpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcontent',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
    ]
