# Generated by Django 5.0.7 on 2024-08-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0018_alter_formcontent_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Контакты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
        migrations.CreateModel(
            name='FooterPage',
            fields=[
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Футер',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_page.section',),
        ),
    ]
