# Generated by Django 5.0.7 on 2024-08-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_contactpage_footerpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(choices=[('hip', 'Протез бедра'), ('leg', 'Протез голени'), ('arm', 'Протез руки'), ('sport', 'Протез спортивный'), ('swim', 'Протез купальный'), ('main', 'Главная'), ('about', 'О компании'), ('interview', 'Интервью с клиентами'), ('contacts', 'Контакты'), ('footer', 'Футер')], max_length=30, null=True, verbose_name='Страница'),
        ),
    ]
