# Generated by Django 5.0.7 on 2024-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_alter_section_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buttoncontent',
            old_name='data',
            new_name='field_1',
        ),
        migrations.AddField(
            model_name='buttoncontent',
            name='field_2',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Текст кнопки'),
        ),
    ]
