# Generated by Django 5.0.7 on 2024-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_rename_data_buttoncontent_field_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttoncontent',
            name='field_1',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='buttoncontent',
            name='field_2',
            field=models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Текст кнопки'),
        ),
    ]
