# Generated by Django 5.0.7 on 2024-08-02 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название тега')),
                ('dec_tag', models.CharField(default=' ', max_length=15, verbose_name='Декларированный тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блога')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Краткое описание блога')),
                ('content', models.TextField(verbose_name='Содержание блога')),
                ('image', models.ImageField(blank=True, upload_to='blog_images/', verbose_name='Изображение')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blogs', to='blog.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
