# Generated by Django 5.0.7 on 2024-08-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_slug_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sub_title',
            field=models.TextField(verbose_name='Краткое описание статьи'),
        ),
    ]
